language: generic
env: MY_BEDROOM=$HOME/bedroom SCRIPT_HOME=$MY_BEDROOM/script PYENV_HOME=$HOME/.pyenv PYENV_VERSIONS=$PYENV_HOME/versions PYTHON_3_VERSION=3.6.3 PYTHON_2_VERSION=2.7.14 BINTRAY_USER_NAME=athrunsun OS_NAME=osx
branches:
  only:
  - master
matrix:
  include:
  - os: osx
    osx_image: xcode6.4
  - os: osx
    osx_image: xcode7.3
  - os: osx
    osx_image: xcode8.1
install:
- mkdir $MY_BEDROOM
- ". $TRAVIS_BUILD_DIR/clone.sh"
- rm -rf $HOME/.pyenv
script:
- ". install_python.sh"
- ". upload_to_bintray.sh"
